### ISSUE TITLE
Question about the difference between rendered_depth and depth_mono.

### ISSUE THREAD

**Issue by XOURTNEY** [Fictionarry/DNGaussian#11]
Hello, jiahe.
Thanks for your amazing work!

I'm a little confused about the depth loss part. I follow the guide and got the 'drum' dataset and its depth_mono. When training around 5500, I found that the rendered_depth had a big difference with depth_mono. 
It seems that on those sides of the diagonal edge, depth went 30->10, but depth_mono went 30->150. Somehow I feel like they were like complementary for each other？
(感觉两个深度的数量级差了一位，然后他俩深浅的算法似乎是相反的)

Are those numbers reasonable? Or that I might have done datasets wrong. If that's right, I wonder why this is reasonable. Thank you so much!!

非常感谢
![屏幕截图 2024-03-27 180829](https://github.com/Fictionarry/DNGaussian/assets/59019590/703b89ff-bad5-4edd-b427-97866308fc73)
![屏幕截图 2024-03-27 180838](https://github.com/Fictionarry/DNGaussian/assets/59019590/4c6f8d48-20ca-4214-93c2-50edf7293819)

**Comment by XOURTNEY** [comment]
btw, loss and psnr are fair enough.
[ITER 4500] Evaluating train: L1 0.01433685850352049 PSNR 26.546026611328127 [27/03 18:06:14]
Training progress:  92%|#########2| 5550/6000 [03:30<00:09, 45.02it/s, Loss=0.0348320]

**Comment by Fictionarry** [comment]
Hi, since the monocular depth predicted by DPT lacks absolute scale, it cannot aligned with the rendered depth in the value range. This scale ambiguity also exists in other monocular depth-regularized works and can be relieved by scale-invariant depth losses like our depth normalization. And since the near positions are represented with large values and far places with 0 in the predicted depth maps from DPT, which is opposite to the rendered depth, it should be reversed while calculating depth loss.
