### ISSUE TITLE
Can depth regularization be used for multi-view setting?

### ISSUE THREAD

**Issue by YiningPeng** [Fictionarry/DNGaussian#33]
Hello, excellent job! I know it's an algorithm for few-shot rendering. But I want to apply the depth regularization to the task where the input is multiple images. However, the results of my experiments are somewhat degraded compared to 3dgs. Do you think that the depth regularization in this paper can be useful for multi-view setting? Or could you give me some insights? Thank you!

**Comment by Fictionarry** [comment]
Hi, we have also explored what would happen if the number of input views increases, and found that the performance of raw 3DGS would gradually exceed our method if the hyperparameters are fixed, as shown in the last parts of the supplementary material. I consider this is raised by 1) photometric consistency can gradually provide more information than from monocular depth. 2) monocular depth is not very accurate, thus more errors would be introduced. 

If the views are extremely dense, such as using all the tens or hundreds of views in LLFF, DTU, MipNeRF360 and so on, depth would be useless, since all information monocular depth can provide can also be learned between dense multiple views.

Despite that, in our further exploration, monocular depth can still provide useful geometry cues when the view coverage is not so dense, especially when some regions are just covered by one or two or a few views. The first thing to do is decrease `--position_lr_init` and `--position_lr_final`, which we set to a large number to facilitate depth regularization for sparse view setting. Then, you can also use SfM point cloud initialization the same as 3DGS to replace the random initialization in our work, as this is no longer needed if views are sufficient. Refer to the difference between `run_llff.sh` and `run_llff_mvs.sh`. The latter one is written for using a stronger initialization, which is somehow like the situation where view increases.

**Comment by YiningPeng** [comment]
Your insights have been very helpful to me! Thank you for your detailed answer!
